# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="edit-server-htmlize"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="(de)HTMLization hooks for edit-server.el"

HOMEPAGE="https://github.com/frobtech/edit-server-htmlize"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/edit-server"
RDEPEND="app-emacs/edit-server"
