# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="simple-paren"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Non-electrical insert paired delimiter, wrap"

HOMEPAGE="https://github.com/andreas-roehler/simple-paren"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
