# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="opencc"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="中文简繁转换 <-> 中文簡繁轉換 (Convert Chinese with OpenCC)"

HOMEPAGE="https://github.com/xuchunyang/emacs-opencc"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
