# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="single"
REALNAME="org-emms"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Play multimedia files from org-mode"

HOMEPAGE="https://gitlab.com/jagrg/org-emms"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
