# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="snapshot-timemachine"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Step through (Btrfs, ZFS, ...) snapshots of files"

HOMEPAGE="https://github.com/mrBliss/snapshot-timemachine"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
