# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="helm-clojuredocs"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="search for help in clojuredocs.org"

HOMEPAGE="https://github.com/mbuczko/helm-clojuredocs"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/edn
	app-emacs/helm"
RDEPEND="app-emacs/edn
	app-emacs/helm"
