# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="xcode-project"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A package for reading Xcode project files."

HOMEPAGE="https://github.com/nhojb/xcode-project.git"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
