# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="netease-music"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="listen netease music"

HOMEPAGE="https://github.com/nicehiro/netease-music"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/names"
RDEPEND="app-emacs/names"
