# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="threes"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A clone of Threes (a tiny puzzle game)"

HOMEPAGE="https://github.com/xuchunyang/threes.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/seq"
RDEPEND="app-emacs/seq"
