# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="openfoam"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="OpenFOAM files and directories"

HOMEPAGE="https://github.com/ralph-schleicher/emacs-openfoam"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
