# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="validate-html"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Compilation mode for W3C HTML Validator"

HOMEPAGE="https://github.com/arthurgleckler/validate-html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
