# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="test-cockpit"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A command center to run tests of a software project"

HOMEPAGE="https://github.com/johannes-mueller/test-cockpit.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/projectile
	app-emacs/toml"
RDEPEND="app-emacs/projectile
	app-emacs/toml"
