# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="sphinx-frontend"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Launch build process for rst documents via sphinx."

HOMEPAGE="https://github.com/kostafey/sphinx-frontend"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
