# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="el-spec"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="ruby's rspec like syntax test frame work"

HOMEPAGE="https://github.com/uk-ar/el-spec"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
