# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="single"
REALNAME="centered-window"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Center the text when theres only one window"

HOMEPAGE="https://github.com/anler/centered-window-mode"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
