# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="tmsu"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A basic TMSU interface"

HOMEPAGE="https://github.com/vifon/tmsu.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
