# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="unicad"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="An elisp port of Mozilla Universal Charset Auto Detector"

HOMEPAGE="https://github.com/ukari/unicad"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/nadvice"
RDEPEND="app-emacs/nadvice"
