# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="pkg-info"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Information about packages"

HOMEPAGE="https://github.com/lunaryorn/pkg-info.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/epl"
RDEPEND="app-emacs/epl"
