# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="drone"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Launch your drone test suite if drone.yml is present"

HOMEPAGE="https://github.com/olymk2/emacs-drone"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
