# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="unipoint"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="a simple way to insert unicode characters by TeX name"

HOMEPAGE="https://github.com/apgwoz/unipoint"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
