# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="frameshot"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Take screenshots of a frame"

HOMEPAGE="https://github.com/tarsius/frameshot"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/compat"
RDEPEND="app-emacs/compat"
