# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="flucui-themes"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Custom theme inspired by the Flat UI palette"

HOMEPAGE="https://github.com/MetroWind/flucui-theme"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
