# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="session"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="use variables, registers and buffer places across sessions"

HOMEPAGE="http://emacs-session.sourceforge.net/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
