# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="disaster"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Disassemble C, C++ or Fortran code under cursor"

HOMEPAGE="https://github.com/jart/disaster"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
