# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="automoji"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Discord-like emoji completion"

HOMEPAGE="https://github.com/Dev380/automoji-el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
