# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="diminish"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Diminished modes are minor modes with no modeline display"

HOMEPAGE="https://github.com/myrjola/diminish.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
