BDEPEND=>=app-editors/emacs-25.3:*
DEFINED_PHASES=compile configure install postinst postrm prepare setup test unpack
DESCRIPTION=Major mode for editing Docker's Dockerfiles
EAPI=8
HOMEPAGE=https://github.com/spotify/dockerfile-mode
INHERIT=g-sorcery gs-elpa
KEYWORDS=~amd64 ~x86
RDEPEND=>=app-editors/emacs-25.3:*
SLOT=0
SRC_URI=https://melpa.org/packages/dockerfile-mode-20220822.2021.tar
_eclasses_=g-sorcery	692c9ad583c66d03e7c0e8b3b106a435	elisp-common	dcd21c5d379fc2217e95f529504c5fe0	elisp	7190c722d9e06fabcae26ef1e1dc9183	gs-elpa	df4b672ca6bb8e009e294018c3bee8bf
_md5_=e32d20559202050a1adfdf21bdd0641f
