# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="latex-preview-pane"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Makes LaTeX editing less painful by providing a updatable preview pane"

HOMEPAGE="http://www.emacswiki.org/emacs/LaTeXPreviewPane"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
