# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="dired-rmjunk"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A home directory cleanup utility for Dired."

HOMEPAGE="https://git.sr.ht/~jakob/dired-rmjunk"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
