# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="look-dired"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Extensions to look-mode for dired buffers"

HOMEPAGE="https://github.com/vapniks/look-dired"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/look-mode"
RDEPEND="app-emacs/look-mode"
