# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="pomo-cat"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Pomodoro timer with cat-themed breaks"

HOMEPAGE="https://github.com/kn66/pomo-cat.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/popon
	app-emacs/posframe"
RDEPEND="app-emacs/popon
	app-emacs/posframe"
