# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="init-dir"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Init directory instead of just a single file"

HOMEPAGE="http://github.com/chaosemer/init-dir"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/benchmark-init"
RDEPEND="app-emacs/benchmark-init"
