# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="ox-impress-js"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="impress.js Back-End for Org Export Engine"

HOMEPAGE="https://github.com/kinjo/org-impress-js.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/org-mode"
RDEPEND="app-emacs/org-mode"
