# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="auto-complete-nxml"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="do completion by auto-complete.el on nXML-mode"

HOMEPAGE="https://github.com/aki2o/auto-complete-nxml"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/auto-complete"
RDEPEND="app-emacs/auto-complete"
