# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="docker-tramp"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="TRAMP integration for docker containers"

HOMEPAGE="https://github.com/emacs-pe/docker-tramp.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
