# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="aria2"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Control aria2c commandline tool from Emacs"

HOMEPAGE="https://bitbucket.org/ukaszg/aria2-mode"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
