# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="shell-split-string"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Split strings using shell-like syntax"

HOMEPAGE="https://github.com/10sr/shell-split-string-el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
