# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="psession"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Persistent save of elisp objects."

HOMEPAGE="https://github.com/thierryvolpiatto/psession"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/async"
RDEPEND="app-emacs/async"
