# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="erc-terminal-notifier"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="OSX notifications via the terminal-notifier gem for Emacs ERC."

HOMEPAGE="http://github.com/julienXX/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
