# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="headlong"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="reckless completion"

HOMEPAGE="https://github.com/abo-abo/headlong"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
