# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="single"
REALNAME="cargo-transient"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A transient UI for Cargo, Rusts package manager"

HOMEPAGE="https://github.com/peterstuart/cargo-transient"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
