# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="ace-jump-helm-line"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Ace-jump to a candidate in helm window"

HOMEPAGE="https://github.com/cute-jumper/ace-jump-helm-line"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/avy
	app-emacs/helm"
RDEPEND="app-emacs/avy
	app-emacs/helm"
