# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="pd-remote"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Pd remote control helper"

HOMEPAGE="https://github.com/agraef/pd-remote"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/faust-mode
	app-emacs/lua-mode"
RDEPEND="app-emacs/faust-mode
	app-emacs/lua-mode"
