# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="metaweblog"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="An XML-RPC MetaWeblog and WordPress API client"

HOMEPAGE="https://github.com/org2blog/org2blog"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
