# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="comint-intercept"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Intercept input in comint-mode"

HOMEPAGE="https://github.com/hying-caritas/comint-intercept"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
