# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="cframe"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Customize a frame and fast switch size and positions"

HOMEPAGE="https://github.com/plandes/cframe"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/buffer-manage
	app-emacs/dash"
RDEPEND="app-emacs/buffer-manage
	app-emacs/dash"
