# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="notmuch-labeler"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Improve notmuch way of displaying labels"

HOMEPAGE="https://github.com/DamienCassou/notmuch-labeler"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/notmuch"
RDEPEND="app-emacs/notmuch"
