# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="ocaml-eglot"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="An OCaml companion for Eglot"

HOMEPAGE="https://github.com/tarides/ocaml-eglot"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
