# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="oauth"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="OAuth 1.0 client library"

HOMEPAGE="https://github.com/fvdbeek/emacs-oauth"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
