# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="lpy"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A lispy interface to Python"

HOMEPAGE="https://github.com/abo-abo/lpy"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/lispy"
RDEPEND="app-emacs/lispy"
