# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="smex"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="M-x interface with Ido-style fuzzy matching."

HOMEPAGE="http://github.com/nonsequitur/smex/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
