# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="trashed"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Viewing/editing system trash can"

HOMEPAGE="https://github.com/shingo256/trashed"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
