# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="log4e"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="provide logging framework for elisp"

HOMEPAGE="https://github.com/aki2o/log4e"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
