# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="total-recall"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Spaced repetition system"

HOMEPAGE="https://github.com/phf-1/total-recall"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
