# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="pipenv"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A Pipenv porcelain"

HOMEPAGE="https://github.com/pwalsh/pipenv.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/s
	app-emacs/pyvenv
	app-emacs/load-env-vars"
RDEPEND="app-emacs/s
	app-emacs/pyvenv
	app-emacs/load-env-vars"
