# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="current-window-only"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Open things only in the current window"

HOMEPAGE="https://github.com/FrostyX/current-window-only"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
