# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="project-explorer"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A project explorer sidebar"

HOMEPAGE="https://github.com/sabof/project-explorer"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/es-lib
	app-emacs/es-windows"
RDEPEND="app-emacs/es-lib
	app-emacs/es-windows"
