# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="lisp-local"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Allow different Lisp indentation in each buffer"

HOMEPAGE="https://github.com/lispunion/emacs-lisp-local"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
