# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="xkcd"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="View xkcd from Emacs"

HOMEPAGE="https://github.com/vibhavp/emacs-xkcd"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
