# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="el-init"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A loader inspired by init-loader"

HOMEPAGE="https://github.com/HKey/el-init"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/anaphora"
RDEPEND="app-emacs/anaphora"
