# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="ob-axiom"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="An org-babel backend for the axiom-environment system"

HOMEPAGE="https://bitbucket.org/pdo/axiom-environment"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/axiom-environment"
RDEPEND="app-emacs/axiom-environment"
