# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="haskell-tab-indent"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="tab-based indentation for haskell-mode"

HOMEPAGE="https://spwhitton.name/tech/code/haskell-tab-indent/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
