# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="parse-it"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Basic Parser in Emacs Lisp"

HOMEPAGE="https://github.com/jcs-elpa/parse-it"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/s"
RDEPEND="app-emacs/s"
