# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="php-cs-fixer"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="php-cs-fixer wrapper."

HOMEPAGE="https://github.com/OVYA/php-cs-fixer"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
