# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="elscreen-fr"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Use frame title as screen tab"

HOMEPAGE="http://github.com/rocher/elscreen-fr"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/elscreen
	app-emacs/seq"
RDEPEND="app-emacs/elscreen
	app-emacs/seq"
