# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="epc"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A RPC stack for the Emacs Lisp"

HOMEPAGE="https://github.com/kiwanami/emacs-epc"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/concurrent
	app-emacs/ctable"
RDEPEND="app-emacs/concurrent
	app-emacs/ctable"
