# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="ctags-update"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="(auto) update TAGS in parent directory using exuberant-ctags"

HOMEPAGE="https://github.com/jixiuf/ctags-update"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
