# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="vc-hgcmd"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="VC mercurial backend that uses hg command server"

HOMEPAGE="https://github.com/muffinmad/emacs-vc-hgcmd"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
