# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="llama-cpp"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A client for llama-cpp server"

HOMEPAGE="https://github.com/kurnevsky/llama-cpp.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/dash"
RDEPEND="app-emacs/dash"
