# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="xref-rst"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Lookup reStructuredText symbols"

HOMEPAGE="https://codeberg.org/ideasman42/emacs-xref-rst"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
