# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="term-manager"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Contextual terminal management"

HOMEPAGE="https://www.github.com/IvanMalison/term-manager"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/dash"
RDEPEND="app-emacs/dash"
