# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="aider"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Interact with Aider: AI pair programming made simple"

HOMEPAGE="https://github.com/tninja/aider.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/transient
	app-emacs/magit
	app-emacs/markdown-mode"
RDEPEND="app-emacs/transient
	app-emacs/magit
	app-emacs/markdown-mode"
