# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="hyperspace"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Get there from here"

HOMEPAGE="https://github.com/ieure/hyperspace-el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/s"
RDEPEND="app-emacs/s"
