# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="slime"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Superior Lisp Interaction Mode for Emacs"

HOMEPAGE="https://github.com/slime/slime"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/macrostep"
RDEPEND="app-emacs/macrostep"
