# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="semaphore-promise"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="semaphore integration with promise"

HOMEPAGE="http://github.com/webnf/semaphore.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/semaphore
	app-emacs/promise"
RDEPEND="app-emacs/semaphore
	app-emacs/promise"
