# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="json-rpc-server"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Server-side JSON-RPC library."

HOMEPAGE="https://github.com/jcaw/json-rpc-server.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
