# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="leaf-defaults"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Awesome leaf config collections"

HOMEPAGE="https://github.com/conao3/leaf-defaults.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/leaf
	app-emacs/leaf-keywords"
RDEPEND="app-emacs/leaf
	app-emacs/leaf-keywords"
