# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="buffer-name-relative"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Relative buffer names"

HOMEPAGE="https://codeberg.com/ideasman42/emacs-buffer-name-relative"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
