# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="external-dict"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Query external dictionary like goldendict, Bob.app etc"

HOMEPAGE="https://repo.or.cz/external-dict.el.git"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
