# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="edit-at-point"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="edit(copy,cut..) current things(word,symbol..) under cursor"

HOMEPAGE="http://github.com/enoson/edit-at-point.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
