# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="orgtbl-join"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Join columns from another Org Mode table"

HOMEPAGE="https://github.com/tbanel/orgtbljoin/blob/master/README.org"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
