# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="dynamic-spaces"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="When editing, don't move text separated by spaces"

HOMEPAGE="https://github.com/Lindydancer/dynamic-spaces"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
