# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="dizzee"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A more pleasant way to manage your project's subprocesses in Emacs."

HOMEPAGE="https://github.com/davidmiller/dizzee"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
