# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="zk"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Functions for working with Zettelkasten-style linked notes"

HOMEPAGE="https://github.com/localauthor/zk"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
