# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="single"
REALNAME="zombie"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="major mode for editing OMBIE programs"

HOMEPAGE="http://hins11.yu-yake.com/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
