# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="single"
REALNAME="org-dashboard"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Visually summarie progress in org files"

HOMEPAGE="http://github.com/bard/org-dashboard"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
