# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="web-completion-data"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Shared completion data for ac-html and company-web"

HOMEPAGE="https://github.com/osv/web-completion-data"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
