# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="bar-cursor"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="package used to switch block cursor to a bar"

HOMEPAGE="https://github.com/ajsquared/bar-cursor"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
