# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="org-zettelkasten"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A Zettelkasten mode leveraging Org"

HOMEPAGE="https://sr.ht/~ymherklotz/org-zettelkasten"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/org-mode"
RDEPEND="app-emacs/org-mode"
