# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="org-jami-bot"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Capture GNU Jami messages as notes and todos in Org mode"

HOMEPAGE="https://gitlab.com/hperrey/org-jami-bot"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/jami-bot"
RDEPEND="app-emacs/jami-bot"
