# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="define-word"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="display the definition of word at point."

HOMEPAGE="https://github.com/abo-abo/define-word"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
