# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="pretty-sha-path"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Prettify Guix/Nix store paths"

HOMEPAGE="https://gitorious.org/alezost-emacs/pretty-sha-path"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
