# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="lsp-intellij"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="intellij lsp client"

HOMEPAGE="https://github.com/Ruin0x11/lsp-intellij"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/lsp-mode"
RDEPEND="app-emacs/lsp-mode"
