# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="winum"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Navigate windows and frames using numbers."

HOMEPAGE="http://github.com/deb0ch/winum.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/dash"
RDEPEND="app-emacs/dash"
