# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="elgrep"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Searching files for regular expressions"

HOMEPAGE="https://github.com/TobiasZawada/elgrep"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/async"
RDEPEND="app-emacs/async"
