# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="outshine"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="outline with outshine outshines outline"

HOMEPAGE="https://github.com/alphapapa/outshine"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/outorg"
RDEPEND="app-emacs/outorg"
