# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="cfengine-code-style"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="C code style for CFEngine project."

HOMEPAGE="https://github.com/cfengine/core"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
