# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="make-color"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Alternative to picking color - update fg/bg color by pressing r/g/b/... keys"

HOMEPAGE="https://github.com/alezost/make-color.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
