# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="jtags"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Enhanced tags functionality for Java development"

HOMEPAGE="https://git.code.sf.net/p/jtags/code"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
