# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="varuga"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Send ical calendar invites by email"

HOMEPAGE="https://git.systemreboot.net/varuga/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
