# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="window-jump"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Move left/right/up/down through your windows."

HOMEPAGE="https://github.com/chumpage/chumpy-windows"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
