# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="bpe"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Blog from Org mode to Blogger"

HOMEPAGE="https://github.com/yuutayamada/bpe"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
