# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="org-upcoming-modeline"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Show next org event in mode line"

HOMEPAGE="https://github.com/unhammer/org-upcoming-modeline"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/ts
	app-emacs/org-ql"
RDEPEND="app-emacs/ts
	app-emacs/org-ql"
