# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="ros"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Package to write code for ROS systems"

HOMEPAGE="https://github.com/DerBeutlin/ros.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
