# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="gtk-variant"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Set the GTK theme variant (titlebar color)"

HOMEPAGE="https://github.com/bepvte/gtk-variant.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
