# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="mcp-server-lib"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Model Context Protocol server library"

HOMEPAGE="https://github.com/laurynas-biveinis/mcp-server-lib.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
