# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="empos"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Locate bibtex citations from within emacs"

HOMEPAGE="http://github.com/dimalik/empos/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
