# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="gif-screencast"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="One-frame-per-action GIF recording"

HOMEPAGE="https://gitlab.com/ambrevar/emacs-gif-screencast"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
