# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="sly-overlay"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Overlay Common Lisp evaluation results"

HOMEPAGE="https://git.sr.ht/~fosskers/sly-overlay"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/sly"
RDEPEND="app-emacs/sly"
