# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="elfeed"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="an Emacs Atom/RSS feed reader"

HOMEPAGE="https://github.com/skeeto/elfeed"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
