# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="org-starter-swiper"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Swiper for org-starter"

HOMEPAGE="https://github.com/akirak/org-starter"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/swiper
	app-emacs/org-starter"
RDEPEND="app-emacs/swiper
	app-emacs/org-starter"
