# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="flycheck-nim"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Defines a flycheck syntax checker for nim"

HOMEPAGE="https://github.com/ALSchwalm/flycheck-nim"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/dash
	app-emacs/flycheck"
RDEPEND="app-emacs/dash
	app-emacs/flycheck"
