# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="sas-py"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="SAS with SASPy"

HOMEPAGE="https://github.com/ShuguangSun/sas-py"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/ess"
RDEPEND="app-emacs/ess"
