# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="bibliothek"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Managing a digital library of PDFs"

HOMEPAGE="https://dev.gkayaalp.com/elisp/index.html#bibliothek-el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/pdf-tools
	app-emacs/a"
RDEPEND="app-emacs/pdf-tools
	app-emacs/a"
