# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="bbdb-vcard"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="vCard import/export for BBDB"

HOMEPAGE="https://github.com/tohojo/bbdb-vcard"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/bbdb"
RDEPEND="app-emacs/bbdb"
