# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="babel"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="interface to web translation services such as Babelfish"

HOMEPAGE="http://github.com/juergenhoetzel/babel"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
