# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="pcomplete-extension"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="additional completion for pcomplete"

HOMEPAGE="https://github.com/thierryvolpiatto/pcomplete-extension"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
