# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="ipython-shell-send"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Send code (including magics) to ipython shell"

HOMEPAGE="https://github.com/jackkamm/ipython-shell-send-el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
