# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="casual-lib"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Library routines for Casual user interfaces"

HOMEPAGE="https://github.com/kickingvegas/casual-lib"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/transient"
RDEPEND="app-emacs/transient"
