# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="korean-holidays"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Korean holidays for calendar."

HOMEPAGE="https://github.com/tttuuu888/korean-holidays"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
