# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="romkan"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Romaji/Kana conversion library"

HOMEPAGE="https://github.com/gicrisf/romkan.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
