# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="musicbrainz"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="MusicBrainz API interface"

HOMEPAGE="https://github.com/zzkt/metabrainz"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/request"
RDEPEND="app-emacs/request"
