# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="haskell-emacs-base"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Haskell functions from Prelude"

HOMEPAGE="https://github.com/knupfer/haskell-emacs/modules/base"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/haskell-emacs"
RDEPEND="app-emacs/haskell-emacs"
