# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="bug-reference-github"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Set \`bug-reference-url-format' in Github repos"

HOMEPAGE="https://github.com/arnested/bug-reference-github"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
