# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="config-parser"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="a library for parsing config file"

HOMEPAGE="https://github.com/lujun9972/el-config-parser"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
