# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="template-dumper"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Create files from yasnippet templates"

HOMEPAGE="https://resultsmotivated.com/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/yasnippet
	app-emacs/f"
RDEPEND="app-emacs/yasnippet
	app-emacs/f"
