# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="gather"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Gather string in buffer."

HOMEPAGE="https://github.com/mhayashi1120/Emacs-gather/raw/master/gather.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
