# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="org-random-todo"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="show a random TODO (with alert) every so often"

HOMEPAGE="https://github.com/unhammer/org-random-todo"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/alert"
RDEPEND="app-emacs/alert"
