# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="oj"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Competitive programming tools client for AtCoder, Codeforces"

HOMEPAGE="https://github.com/conao3/oj.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/quickrun"
RDEPEND="app-emacs/quickrun"
