# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="alert"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Growl-style notification system for Emacs"

HOMEPAGE="https://github.com/jwiegley/alert"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/gntp
	app-emacs/log4e"
RDEPEND="app-emacs/gntp
	app-emacs/log4e"
