# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="morlock"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="More font-lock keywords for elisp"

HOMEPAGE="https://github.com/tarsius/morlock"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/compat"
RDEPEND="app-emacs/compat"
