# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="handle"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A handle for major-mode generic functions."

HOMEPAGE="https://gitlab.com/jjzmajic/handle"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/parent-mode"
RDEPEND="app-emacs/parent-mode"
