# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="totp-auth"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="RFC6238 TOTP"

HOMEPAGE="https://gitlab.com/fledermaus/totp.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/base32"
RDEPEND="app-emacs/base32"
