# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="iso-639"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="ISO 639"

HOMEPAGE="https://codeberg.org/Jaft/emacs-iso-639"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/levenshtein"
RDEPEND="app-emacs/levenshtein"
