# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="helm-sql-connect"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Choose a database to connect to via Helm."

HOMEPAGE="https://github.com/eric-hansen/helm-sql-connect"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/helm"
RDEPEND="app-emacs/helm"
