# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="import-js"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Import Javascript dependencies"

HOMEPAGE="http://github.com/Galooshi/emacs-import-js/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/grizzl"
RDEPEND="app-emacs/grizzl"
