# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="idle-require"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="load elisp libraries while Emacs is idle"

HOMEPAGE="http://nschum.de/src/emacs/idle-require/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
