# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="move-text"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Move current line or region with M-up or M-down."

HOMEPAGE="https://github.com/emacsfodder/move-text"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
