# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="org-alert"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Notify org deadlines via notify-send"

HOMEPAGE="https://github.com/spegoraro/org-alert"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/org-mode
	app-emacs/alert"
RDEPEND="app-emacs/org-mode
	app-emacs/alert"
