# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="font-lock-studio"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="interactive debugger for Font Lock keywords."

HOMEPAGE="https://github.com/Lindydancer/font-lock-studio"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
