# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="helm-shell-history"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Find shell history from helm"

HOMEPAGE="https://github.com/yuutayamada/helm-shell-history"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/helm"
RDEPEND="app-emacs/helm"
