# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="jami-bot"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="An extendable chat bot for the private messenger GNU Jami"

HOMEPAGE="https://gitlab.com/hperrey/jami-bot"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
