# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="i-ching"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="The Book of Changes"

HOMEPAGE="https://github.com/zzkt/i-ching"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/request"
RDEPEND="app-emacs/request"
