# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="ddskk-posframe"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Show Henkan tooltip for ddskk via posframe"

HOMEPAGE="https://github.com/conao3/ddskk-posframe.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/posframe
	app-emacs/ddskk"
RDEPEND="app-emacs/posframe
	app-emacs/ddskk"
